"""协议层（严格遵循《多模态采集板通讯协议定义》v1）。

- magic = 0xAA55
- CRC16-CCITT（多项式 0x1021，初值 0xFFFF）
- type 0x01~0xFF（参见 spec.py）
- 二进制 payload（不再使用 JSON）
"""

from .spec import (
    MAGIC, PROTO_VER, HEADER_SIZE,
    TYPE_DATA_ECG, TYPE_DATA_PVDF, TYPE_DATA_RESISTIVE,
    TYPE_HR_RR, TYPE_LEAD_OFF, TYPE_SYS_STATUS, TYPE_DEVICE_INFO,
    TYPE_BATTERY_WARN, TYPE_OTA_DATA, TYPE_OTA_ACK,
    TYPE_ACK, TYPE_CMD, TYPE_HEARTBEAT, TYPE_PARAM_CFG,
    TYPE_VERSION_NEGO, TYPE_ERROR,
    CMD_START_ACQ, CMD_STOP_ACQ, CMD_ONCE_ACQ,
    CMD_READ_STATUS, CMD_READ_INFO, CMD_READ_BAT, CMD_READ_LEAD,
    CMD_RESET_MCU, CMD_RESET_SENSOR,
    CMD_ENTER_OTA, CMD_EXIT_OTA,
    CMD_SET_LCD, CMD_SET_TIMEOUT, CMD_PROBE, CMD_EMERGENCY_STOP,
)
from .codec import Frame, FrameCodec
from .errors import ProtocolError

__all__ = [
    "MAGIC", "PROTO_VER", "HEADER_SIZE",
    "TYPE_DATA_ECG", "TYPE_DATA_PVDF", "TYPE_DATA_RESISTIVE",
    "TYPE_HR_RR", "TYPE_LEAD_OFF", "TYPE_SYS_STATUS", "TYPE_DEVICE_INFO",
    "TYPE_BATTERY_WARN", "TYPE_OTA_DATA", "TYPE_OTA_ACK",
    "TYPE_ACK", "TYPE_CMD", "TYPE_HEARTBEAT", "TYPE_PARAM_CFG",
    "TYPE_VERSION_NEGO", "TYPE_ERROR",
    "CMD_START_ACQ", "CMD_STOP_ACQ", "CMD_ONCE_ACQ",
    "CMD_READ_STATUS", "CMD_READ_INFO", "CMD_READ_BAT", "CMD_READ_LEAD",
    "CMD_RESET_MCU", "CMD_RESET_SENSOR",
    "CMD_ENTER_OTA", "CMD_EXIT_OTA",
    "CMD_SET_LCD", "CMD_SET_TIMEOUT", "CMD_PROBE", "CMD_EMERGENCY_STOP",
    "Frame", "FrameCodec",
    "ProtocolError",
]
